services:
  web:
    build: .
    # Overwrites the default CMD in the Dockerfile with Django’s dev server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8009:8000"
    depends_on:
      - db
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: c4d_db_it_3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      DJANGO_SETTINGS_MODULE: a_core.settings
    # networks:
    #   - c4d_network

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: c4d_db_it_3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    
    volumes:
      - postgres_data:/var/lib/postgresql/data

    # Exposes the Postgres port
    ports:
      - "5432:5432"
    # networks:
    #   - c4d_network
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root 
      # PGADMIN_LISTEN_PORT = 80
    ports:
      - "5050:80"

networks:
  c4d_network:
    driver: bridge

volumes:
  postgres_data:
