# Generated by Django 5.0.7 on 2025-04-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pending_middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
