# Generated by Django 5.0.7 on 2025-02-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='agvsa_clearance_number',
            new_name='clearance_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='security_clearance',
        ),
        migrations.AddField(
            model_name='profile',
            name='clearance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='clearance_level',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Pending', 'Pending'), ('Baseline', 'Baseline'), ('NV1', 'NV1'), ('NV2', 'NV2'), ('PV', 'PV')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('VIC', 'VIC'), ('NSW', 'NSW'), ('ACT', 'ACT'), ('QLD', 'QLD'), ('NT', 'NT'), ('WA', 'WA'), ('SA', 'SA')], max_length=3, null=True),
        ),
    ]
