# Generated by Django 5.0.7 on 2025-04-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_pending_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name_change_done',
            field=models.BooleanField(default=False, help_text='Set to True by admin once a pending name-change request has been processed.'),
        ),
    ]
