# Generated by Django 5.0.7 on 2025-02-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skill_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill_sets',
            field=models.TextField(blank=True, null=True),
        ),
    ]
