# Generated by Django 5.0.7 on 2025-05-06 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_name_change_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skill_level',
        ),
    ]
