# Generated by Django 5.0.7 on 2025-02-27 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_profile_skill_level_profile_skill_sets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="displayname",
        ),
    ]
