# Generated by Django 5.0.7 on 2025-04-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_profile_displayname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='clearance_expiry',
            new_name='clearance_revalidation',
        ),
        migrations.AddField(
            model_name='profile',
            name='clearance_active',
            field=models.BooleanField(default=False),
        ),
    ]
